### ISSUE TITLE
Text Color is not working

### ISSUE THREAD

**Issue by Husam-Burhan** [foex-open-source/fos-tooltip#1]
When you set Text Color to any color value, it will remain white.
I tried to set options.txtColor in JavaScript Initialization Code, but it always white.

Thanks.

**Comment by foex-open-source** [comment]
It's not possible to set the text color through _JavaScript Initialization Code_, it can be done only in the plug-in attributes ( _Text Color_ ).

**Comment by Husam-Burhan** [comment]
Ok, I see.
But it will be nice if plug-in attributes ( Text Color, Background Color ) can support Substitutions: Application, Page Items and System Variables.

Thanks.
